<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="7.0.2" />
    <PackageReference Include="AspNet.Security.OAuth.Spotify" Version="8.2.0" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="4.0.2" />
    <PackageReference Include="Inflatable.Lastfm" Version="1.2.0" />
    <PackageReference Include="Microsoft.ML" Version="4.0.0" />
    <PackageReference Include="Localization.SqlLocalizer" Version="3.1.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.9.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SpotifyAPI.Web" Version="7.2.1" />
    <!-- Optional Auth module, which includes an embedded HTTP Server for OAuth2 -->
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.2.1" />
    <PackageReference Include="AutoMapper" Version="13.0.0" />
    <PackageReference Include="TSGenerator" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../BackgroundServices/BackgroundServices.csproj" />
    <ProjectReference Include="../Player/Player.csproj" />
  </ItemGroup>
</Project>
