using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TSGenerator.Enums;
using TSGenerator.Models;
using TSGenerator.Modules;
using TSGenerator.Services;

namespace TSGenerator
{
    public class TSBuildTask : Task
    {
        /// <summary>
        /// The file path of the compilerconfig.json file
        /// </summary>
        public string FileName { get; set; }

        public string Enviroment { get; set; }

        /// <summary>
        /// Determines the naming style of the generated files and folders
        /// </summary>
        public string PathStyle
        {
            get => _pathStyle.ToString();
            set => _pathStyle = (PathStyle)Enum.Parse(typeof(PathStyle), value);
        }

        /// <summary>
        /// Determines the naming style of the generated properties
        /// </summary>
        public string PropertyStyle
        {
            get => _propertyStyle.ToString();
            set => _propertyStyle = (PropertyStyle)Enum.Parse(typeof(PropertyStyle), value);
        }

        /// <summary>
        /// Comments at the top of each file that it was auto generated
        /// </summary>
        public bool AutoGeneratedTag { get; set; } = true; //default value if one is not provided;


        /// <summary>
        /// Determines whether to generate numeric or string values in typescript enums
        /// </summary>
        public string EnumValues
        {
            get => _enumValues.ToString();
            set => _enumValues = (EnumValues)Enum.Parse(typeof(EnumValues), value);
        }

        protected MessageImportance LoggingImportance { get; } = MessageImportance.High;  //If its not high then there are no logs

        private readonly ConvertService convertService;

        private EnumValues _enumValues = Enums.EnumValues.Default;

        private PathStyle _pathStyle = Enums.PathStyle.Default;
        private PropertyStyle _propertyStyle = Enums.PropertyStyle.CamelCase;

        public TSBuildTask()
        {
            convertService = new ConvertService(
                (string message, LogMessageType logMessageType, object[] messageArgs) =>
                {
                    switch (logMessageType)
                    {
                        case LogMessageType.Error: Log.LogError(message, messageArgs); break;
                        case LogMessageType.Warning: Log.LogWarning(message, messageArgs); break;
                        default: Log.LogMessage(LoggingImportance, message, messageArgs); break;
                    };
                });
        }

        public override bool Execute()
        {
            Log.LogMessage(LoggingImportance, $"{Environment.NewLine}TS Build: Starting..");

            FileInfo configFile = new(FileName);

            if (!configFile.Exists)
            {
                Log.LogWarning(configFile.FullName + " does not exist");
                return true;
            }

            Log.LogMessage(LoggingImportance, $"Begin processing {configFile.Name}");

            var config = new Configuration(configFile);

            Log.LogMessage(LoggingImportance, $"config contains {config.Count()} items..");

            convertService.AutoGeneratedTag = this.AutoGeneratedTag;
            convertService.EnumValues = _enumValues;
            convertService.PathStyle = _pathStyle;
            convertService.PropertyStyle = _propertyStyle;
            convertService.Enviroment = this.Enviroment;

            List<(ModelLoader ModelLoader, BuildConfiguration Config)> modelLoaders = new();
            foreach (var item in config)
            {
                Log.LogMessage(LoggingImportance, $"{item.Source} => {item.Target}");
                var modelLoader = convertService.Read(item);
                modelLoaders.Add((modelLoader, item));
            }

            var allTypes = modelLoaders.SelectMany(e => e.ModelLoader.Models).ToArray();

            foreach (var item in modelLoaders)
            {
                Log.LogMessage(LoggingImportance, $"{item.Config.Source} => {item.Config.Target}");
                _ = convertService.Write(item.ModelLoader, item.Config, allTypes);
            }

            Log.LogMessage(LoggingImportance, $"TS Build: Finished{Environment.NewLine}");
            return true;
        }
    }
}
