using System;
using System.IO;
using System.Threading;
using TSGenerator.Enums;
using TSGenerator.Models;
using TSGenerator.Modules;

namespace TSGenerator.Services
{
    public class ConvertService : ModuleBase
    {
        /// <summary>
        /// Comments at the top of each file that it was auto generated
        /// </summary>
        public bool AutoGeneratedTag { get; set; } = true; //default value if one is not provided;

        /// <summary>
        /// Determines whether to generate numeric or string values in typescript enums
        /// </summary>
        public EnumValues EnumValues { get; internal set; }

        /// <summary>
        /// Determines the naming style of the generated files and folders
        /// </summary>
        public PathStyle PathStyle { get; set; }

        /// <summary>
        /// Determines the naming style of the generated properties
        /// </summary>
        public PropertyStyle PropertyStyle { get; set; }

        public string Enviroment { get; set; }


        public ConvertService(LogAction log)
            : base(log)
        {
        }

        public ModelLoader Read(BuildConfiguration buildConfiguration)
        {
            this.Log($"get convert directory..");
            var convertDirectory = GetConvertDirectory(buildConfiguration.Target.Path);

            return new ModelLoader(buildConfiguration, this.Enviroment, this.Log);
        }

        public ModelConverter Write(ModelLoader modelLoader, BuildConfiguration buildConfiguration, ModelFile[] allTypes)
        {
            this.Log($"get convert directory..");

            var convertDirectory = GetConvertDirectory(buildConfiguration.Target.Path);
            return new ModelConverter(modelLoader.Models, allTypes, convertDirectory, this.PathStyle, this.PropertyStyle, this.EnumValues, this.AutoGeneratedTag, this.Log);
        }

        private string GetConvertDirectory(string directory)
        {
            var dir = Directory.GetCurrentDirectory();

            if (string.IsNullOrEmpty(directory))
            {
                return dir;
            }

            var localdir = System.IO.Path.Combine(dir, directory);

            if (!Directory.Exists(localdir))
            {
            }
            else
            {
                this.Log($"delete existing convert directory {localdir}..");
                DeleteDirectory(localdir, 0);
            }

            this.Log($"create convert directory {localdir}..");
            Directory.CreateDirectory(localdir).Create();
            return localdir;
        }

        private void DeleteDirectory(string path, int iteration)
        {
            foreach (string directory in Directory.GetDirectories(path))
            {
                DeleteDirectory(directory, 0);
            }

            try
            {
                Directory.Delete(path, true);
            }
            catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
            {
                if (iteration >= 10)
                {
                    throw;
                }
                Thread.Sleep(100 * (int)Math.Pow(2, iteration));
                DeleteDirectory(path, ++iteration);
            }
        }
    }
}
