using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using TSGenerator.Enums;
using TSGenerator.Extensions;
using TSGenerator.Models;

namespace TSGenerator.Modules
{
    public class ModelConverter : ModuleBase
    {
        public ModelConverter(IEnumerable<ModelFile> models, ModelFile[] allTypes, string convertDirectory, PathStyle pathStyle, PropertyStyle propertyStyle, EnumValues enumValues, bool autoGeneratedTag, LogAction log)
            : base(log)
        {
            this.PathStyle = pathStyle;
            this.PropertyStyle = propertyStyle;
            this.EnumValues = enumValues;
            this.AutoGeneratedTag = autoGeneratedTag;

            this.Convert(models, allTypes, convertDirectory);
        }

        public PathStyle PathStyle { get; }
        public PropertyStyle PropertyStyle { get; }
        public EnumValues EnumValues { get; }
        public bool AutoGeneratedTag { get; }

        private void Convert(IEnumerable<ModelFile> models, ModelFile[] allModels, string convertDirectory)
        {
            Log("Convert model:");

            if (models == null
                || !models.Any())
            {
                Log("!! models are null or empty..");
                return;
            }

            foreach (var model in models)
            {
                this.Convert(model, allModels, convertDirectory);
            }
        }

        private void Convert(ModelFile model, ModelFile[] allModels, string convertDirectory)
        {
            var directoryPath = convertDirectory;
            DirectoryInfo di = Directory.CreateDirectory(System.IO.Path.Combine(convertDirectory, model.RelativePath.ToString()));
            di.Create();

            string fileName = $"{(PathStyle == PathStyle.Kebab ? model.Name.ToKebabCase() : model.Name.ToCamelCase())}{model.Extension}";
            Log($" -- write model {model.Name}: {di.FullName} => {fileName}");
            string saveDir = System.IO.Path.Combine(directoryPath, fileName);

            TSWriter tsWriter = new(model, this.Log);

            using var stream = GetStream(saveDir, 0);
            using StreamWriter f = new(stream, System.Text.Encoding.UTF8, 1024, false);
            tsWriter.Write(f, allModels, this.AutoGeneratedTag);
        }

        private static FileStream GetStream(string saveDir, int iteration)
        {
            try
            {
                Directory.CreateDirectory(System.IO.Path.GetDirectoryName(saveDir));
                return new FileStream(saveDir, FileMode.Create, FileAccess.Write, FileShare.Read, 4096, FileOptions.SequentialScan);
            }
            catch (UnauthorizedAccessException)
            {
                if (iteration >= 10)
                {
                    throw;
                }
                Thread.Sleep(100 * (int)Math.Pow(2, iteration));
                return GetStream(saveDir, ++iteration);
            }
            catch (DirectoryNotFoundException)
            {
                if (iteration >= 10)
                {
                    throw;
                }
                return GetStream(saveDir, ++iteration);
            }
        }
    }
}
