using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using TSGenerator.Extensions;
using TSGenerator.Models;

namespace TSGenerator.Modules
{
    public class TSWriter : ModuleBase
    {
        public TSWriter(ModelFile modelFile, LogAction log)
            : base(log)
        {
            this.ModelFile = modelFile;
        }

        public ModelFile ModelFile { get; }

        public void Write(StreamWriter streamWriter, ModelFile[] allTypes, bool writeAutoGeneratedTag = false)
        {
            if (writeAutoGeneratedTag)
            {
                streamWriter.WriteLine("/* Auto Generated */");
                streamWriter.WriteLine();
            }

            if (this.ModelFile.Type == null)
            {
                streamWriter.WriteLine("/* Failed to load the model type */");
                return;
            }

            if (this.ModelFile.IsEnum)
            {
                streamWriter.WriteLine("/* enum type */");
                streamWriter.WriteLine();
            }

            if (this.ModelFile.Inheritance != null) streamWriter.WriteLine($"/* inheritance defined in c# class: {string.Join(",", this.ModelFile.Inheritance)} */");
            var inheritance = this.ModelFile.GetInheritance(allTypes);
            if (this.ModelFile.Type?.BaseType != null
                && inheritance != null
                && !inheritance.Contains(this.ModelFile.Type.BaseType))
            {
                streamWriter.WriteLine($"/* Failed to add inheritance for base type: {this.ModelFile.Type.BaseType.FullName} */");
            }

            bool ns = WriteNamespaceStart(streamWriter);
            WriteTypeStart(inheritance, streamWriter, ns);

            if (this.ModelFile.IsEnum) WriteEnum(streamWriter);
            else WriteProperties(streamWriter, allTypes);

            WriteTypeEnd(streamWriter, ns);
            WriteNamespaceEnd(streamWriter);
        }

        private bool WriteNamespaceStart(StreamWriter streamWriter)
        {
            if (!string.IsNullOrEmpty(this.ModelFile.Namespace))
            {
                //streamWriter.WriteIdent(0, $"declare module {this.ModelFile.Namespace} {{");
                streamWriter.WriteIdent(0, $"namespace {this.ModelFile.Namespace} {{");
                return true;
            }

            return false;
        }

        private bool WriteNamespaceEnd(StreamWriter streamWriter)
        {
            if (!string.IsNullOrEmpty(this.ModelFile.Namespace))
            {
                streamWriter.WriteIdent(0, $"}}");
                return true;
            }

            return false;
        }

        private void WriteTypeStart(Type[] inheritance, StreamWriter streamWriter, bool hasNamespace = false, int ident = 4)
        {
            string type = "interface";
            if (this.ModelFile.IsEnum) type = "enum";

            string inheritanceString = "";
            if (inheritance.Length > 0)
            {
                inheritanceString = $" extends {string.Join(", ", inheritance.Select(e => $"{e.Namespace}.{e.ToGenericTypeString()}"))}";
            }

            streamWriter.WriteIdent(hasNamespace ? ident : 0, $"export {type} {this.ModelFile.Type.ToGenericTypeString()}{inheritanceString} {{");
        }

        private static void WriteTypeEnd(StreamWriter streamWriter, bool hasNamespace = false, int ident = 4)
        {
            streamWriter.WriteIdent(hasNamespace ? ident : 0, $"}}");
        }

        private void WriteProperties(StreamWriter streamWriter, ModelFile[] allModels, int ident = 8, bool resolveEnumValues = true)
        {
            var staticFields = this.ModelFile.Type.GetFields(BindingFlags.Static | BindingFlags.Public);
            if (staticFields != null
                && staticFields.Length > 0)
            {
                for (int i = 0; i < staticFields.Length; i++)
                {
                    var staticFieldValue = staticFields[i].GetValue(null);
                    if (staticFieldValue == null) continue;

                    streamWriter.WriteIdent(ident, $"/* found public static field */");
                    streamWriter.WriteIdent(ident, $"{staticFields[i].Name}: '{staticFieldValue}';");
                }
            }

            PropertyInfo[] properties = this.ModelFile.Type.GetProperties();
            foreach (PropertyInfo property in properties)
            {
                var propertyName = property.Name;
                IEnumerable<System.Text.Json.Serialization.JsonPropertyNameAttribute> jsonPropertyAttributes = null;

                try
                {
                    jsonPropertyAttributes = property.GetCustomAttributes<System.Text.Json.Serialization.JsonPropertyNameAttribute>();
                }
                catch (Exception ex)
                {
                    this.Log("Cannot find property: " + propertyName,Enums.LogMessageType.Warning);
                    this.Log($"  {ex.Message}", Enums.LogMessageType.Warning);
                    continue;
                }

                if (jsonPropertyAttributes != null
                    && jsonPropertyAttributes.Any())
                {
                    streamWriter.WriteIdent(ident, $"/* found json property attribute for property name {propertyName} */");
                    propertyName = jsonPropertyAttributes.First().Name;
                }

                var jsonIgnoreAttributes = property.GetCustomAttributes<System.Text.Json.Serialization.JsonIgnoreAttribute>();
                if (jsonIgnoreAttributes != null
                    && jsonIgnoreAttributes.Any())
                {
                    streamWriter.WriteIdent(ident, $"/* found json ignore attribute for property {propertyName} */");
                    continue;
                }

                var type = property.PropertyType;

                bool isEnumerable = type != typeof(String)
                    && type != typeof(string)
                    && typeof(IEnumerable).IsAssignableFrom(type);



                // IEnumerable?
                bool isDictionary = false;
                Type dictionaryKeyType = typeof(string);
                if (isEnumerable)
                {
                    // dictionary
                    if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IDictionary<,>))
                    {
                        streamWriter.WriteIdent(ident, $"/* found generic dictionary type {type.Name} */");
                        isDictionary = true;
                        try
                        {
                            dictionaryKeyType = type.GetGenericArguments()[0];
                            type = type.GetGenericArguments()[1];
                            streamWriter.WriteIdent(ident, $"/* found dictionary type {type.Name} */");
                        }
                        catch
                        {
                            streamWriter.WriteIdent(ident, "/* failed to create single item from dictionary type */");
                        }
                    }
                    else
                    {
                        try
                        {
                            if (type.IsArray) type = type.GetElementType();
                            else type = type.GetGenericArguments().Single();
                        }
                        catch
                        {
                            streamWriter.WriteIdent(ident, "/* failed to create single item from collection type */");
                        }
                    }
                }

                bool hasCustomType = false;
                ModelFile[] targetModels = allModels?.Where(e => e.Type == type).ToArray();
                if (targetModels != null
                    && targetModels.Any())
                {
                    type = targetModels[0].Type;
                    streamWriter.WriteIdent(ident, $"/* found custom type: {type.ToGenericTypeString()} => {string.Join(", ", targetModels.Select(e => $"reative path={e.RelativePath},file={e.Name}{e.Extension}"))} */");
                    hasCustomType = true;
                }

                // nullable?
                var nullableType = Nullable.GetUnderlyingType(type);
                bool isNullable = nullableType != null;
                if (isNullable)
                {
                    type = nullableType;
                }

                if (property.PropertyType.IsEnum
                    && resolveEnumValues)
                {
                    var enumValues = GetEnumValues(property.PropertyType);
                    streamWriter.WriteIdent(ident, $"/* resolve enum values for property {propertyName} */");

                    streamWriter.WriteIdent(ident, $"{propertyName}{(isNullable ? "?" : "")}: {string.Join(" | ", enumValues.Select(e => $"'{e.Item1}'"))};");
                    continue;
                }

                var propertyType = ConvType(type, hasCustomType);

                // IEnumerable?
                if (isEnumerable && !isDictionary) propertyType += "[]";

                streamWriter.WriteIdent(ident, $"/* orign c# type: {property.PropertyType.FullName} */");
                if (isNullable) streamWriter.WriteIdent(ident, $"/* is nullable */");
                if (isEnumerable) streamWriter.WriteIdent(ident, $"/* is enumerable */");

                if (isDictionary) streamWriter.WriteIdent(ident, $"{propertyName}: {{ [key: {ConvType(dictionaryKeyType, false)}]: {propertyType} }};");
                else streamWriter.WriteIdent(ident, $"{propertyName}{(isNullable ? "?" : "")}: {propertyType};");
            }
        }

        private static string ConvType(Type type, bool hasCustomType)
        {
            var tName = type.ToGenericTypeString();
            var propertyType = (type.Name.EndsWith("?") ? tName[0..^1] : tName) ?? "any";
            if (!hasCustomType)
            {
                propertyType = ConvertPropertyType(propertyType);
            }
            else
            {
                propertyType = $"{type.Namespace}.{propertyType}";
            }

            return propertyType;
        }

        private static string ConvertPropertyType(string propertyType)
            => propertyType switch
            {
                "byte" or "sbyte" or "decimal" or "double" or "float" or "int" or "uint" or "long" or "ulong" or "short" or "ushort" or "Byte" or "Decimal" or "Double" or "Int16" or "Int32" or "Int64" or "SByte" or "UInt16" or "UInt32" or "UInt64" => "number",
                "bool" or "Boolean" => "boolean",
                "string" or "char" or "String" or "Char" or "Guid" => "string",
                "DateTime" => "Date",
                _ => "any",
            };

        private static (string, int)[] GetEnumValues(Type type)
        {
            string[] names = Enum.GetNames(type);
            int[] values = Array.ConvertAll((int[])Enum.GetValues(type), Convert.ToInt32);
            var enumData = names.Zip(values).ToArray();
            return enumData;
        }

        private void WriteEnum(StreamWriter streamWriter, int ident = 8)
        {
            var enumData = GetEnumValues(this.ModelFile.Type);
            for (int i = 0; i < enumData.Length; i++)
            {
                streamWriter.WriteIdent(ident, $"{enumData[i].Item1} = {enumData[i].Item2},");
            }
        }
    }
}
