<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<PackageId>TSGenerator</PackageId>
		<BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IsPackable>true</IsPackable>
		
	    <Version>2.0.1</Version>
	
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build.Framework" Version="*" PrivateAssets="All" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="*" PrivateAssets="All" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.0" />
	</ItemGroup>
	
	<ItemGroup>
		<Content Include="build\*.targets" PackagePath="build\" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="ResultTs\" />
	</ItemGroup>

	<Target Name="BeforeTargetsBuild" BeforeTargets="Build">
		<Message Text="TSGenerator: BeforeTargets=Build" Importance="High" />
	</Target>
</Project>
