using Castle.DynamicProxy.Generators.Emitters.SimpleAST;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TSGenerator.Enums;
using TSGenerator.Models;
using TSGenerator.Modules;
using TSGenerator.Services;
using Xunit;

namespace TSGenerator.Test;
public class ConvertServiceTest
{
    public string FileName = "..//..//..//Test//tsgeneratorconfig.json";
    public string FileNameNewVersion = "..//..//..//Test//tsgeneratorconfig2.json";

    [Fact]
    public void OptimalLoading()
    {
        FileInfo configFile = new(FileNameNewVersion);

        var convertService = new ConvertService((string message, LogMessageType logMessageType, object[] messageArgs) => { return; });
        var config = new Configuration(configFile);
        convertService.AutoGeneratedTag = true;
        convertService.EnumValues = EnumValues.Default;
        convertService.PathStyle = PathStyle.Default;
        convertService.PropertyStyle = PropertyStyle.CamelCase;

        List<(ModelLoader ModelLoader, BuildConfiguration Config)> modelLoaders = new();

        foreach (var item in config)
        {
            var modelLoader = convertService.Read(item);
            modelLoaders.Add((modelLoader, item));
        }


        var allTypes = modelLoaders.SelectMany(e => e.ModelLoader.Models).ToArray();

        foreach (var item in modelLoaders)
        {
            _ = convertService.Write(item.ModelLoader, item.Config, allTypes);
        }


        Assert.NotNull(configFile);
    }

    [Fact]
    public void Test()
    {
        FileInfo configFile = new(FileName);

        Assert.NotNull(configFile);

        var convertService = new ConvertService((string message, LogMessageType logMessageType, object[] messageArgs) => { return; } ) ;
        var config = new Configuration(configFile);

        convertService.AutoGeneratedTag = true;
        convertService.EnumValues = EnumValues.Default;
        convertService.PathStyle = PathStyle.Default;
        convertService.PropertyStyle = PropertyStyle.CamelCase;

        List<(ModelLoader ModelLoader, BuildConfiguration Config)> modelLoaders = new();
        foreach (var item in config)
        {
            var modelLoader = convertService.Read(item);
            modelLoaders.Add((modelLoader, item));
        }

        var allTypes = modelLoaders.SelectMany(e => e.ModelLoader.Models).ToArray();

        foreach (var item in modelLoaders)
        {
            _ = convertService.Write(item.ModelLoader, item.Config, allTypes);
        }
    }
}
